project:
  type: website

website:
  title: "website_theme_reprex"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - mycontent.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
